quarkus.application.name=inventory-service-quarkus
quarkus.http.port=${SERVER_PORT:8084}

quarkus.hibernate-orm.multitenant=DATABASE
quarkus.hibernate-orm.datasource=tienda_deportes
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.packages=pe.joedayz.microservicios.inventory.domain

quarkus.datasource."tienda_deportes".db-kind=postgresql
quarkus.datasource."tienda_deportes".jdbc.url=${INVENTORY_DB_TIENDA_DEPORTES_URL:jdbc:postgresql://localhost:5432/inventory_tienda_deportes}
quarkus.datasource."tienda_deportes".username=${INVENTORY_DB_USERNAME:postgres}
quarkus.datasource."tienda_deportes".password=${INVENTORY_DB_PASSWORD:postgres}

quarkus.datasource."libreria_lima".db-kind=postgresql
quarkus.datasource."libreria_lima".jdbc.url=${INVENTORY_DB_LIBRERIA_LIMA_URL:jdbc:postgresql://localhost:5432/inventory_libreria_lima}
quarkus.datasource."libreria_lima".username=${INVENTORY_DB_USERNAME:postgres}
quarkus.datasource."libreria_lima".password=${INVENTORY_DB_PASSWORD:postgres}

quarkus.liquibase."tienda_deportes".change-log=db/changelog.xml
quarkus.liquibase."tienda_deportes".migrate-at-start=true
quarkus.liquibase."libreria_lima".change-log=db/changelog.xml
quarkus.liquibase."libreria_lima".migrate-at-start=true

%test.quarkus.datasource."tienda_deportes".db-kind=h2
%test.quarkus.datasource."tienda_deportes".jdbc.url=jdbc:h2:mem:inventory-deportes;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource."tienda_deportes".username=sa
%test.quarkus.datasource."tienda_deportes".password=

%test.quarkus.datasource."libreria_lima".db-kind=h2
%test.quarkus.datasource."libreria_lima".jdbc.url=jdbc:h2:mem:inventory-libreria;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource."libreria_lima".username=sa
%test.quarkus.datasource."libreria_lima".password=
