{
 "title": "E-commerce · checkout observable",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{uri!~\"/actuator.*|/q/.*\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*|/q/.*\"}[1m])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Circuit breakers OPEN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open\"} == 1)"
    }
   ]
  },
  {
   "title": "Ordenes por status y degradacion",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status, degradation) (increase(orders_placed_total[5m]))",
     "legendFormat": "{{status}} · {{degradation}}"
    }
   ]
  }
 ]
}