server:
  port: 8084

spring:
  application:
    name: inventory-service
  grpc:
    server:
      port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
