apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          image: localhost/joedayz/order-service-spring:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
