quarkus.application.name=catalog-service-quarkus
quarkus.http.port=${SERVER_PORT:8083}

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:catalog-quarkus;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# Native image: H2 driver inicializa en runtime
quarkus.native.additional-build-args=--initialize-at-run-time=org.h2.Driver
