apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky-downstream
  labels:
    app: flaky-downstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaky-downstream
  template:
    metadata:
      labels:
        app: flaky-downstream
    spec:
      containers:
        - name: flaky-downstream
          image: modulo9/flaky-downstream:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: OTEL_TRACES_ENDPOINT
              value: http://otel-collector:4318/v1/traces
            - name: OTEL_LOGS_ENDPOINT
              value: http://otel-collector:4318/v1/logs
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flaky-downstream
spec:
  selector:
    app: flaky-downstream
  ports:
    - name: http
      port: 8090
      targetPort: http
