server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: catalog-service-webflux
  r2dbc:
    url: ${DB_URL:r2dbc:h2:mem:///catalog-webflux;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
