server:
  port: 8085

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
  grpc:
    client:
      channels:
        inventory:
          address: static://localhost:9090

clients:
  catalog:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    pe.joedayz.microservicios.order.client: DEBUG
